"""anneal-memory: Living memory for AI agents. Episodes compress into identity."""

__version__ = "0.4.7"

from .store import (
    AnnealMemoryError,
    Store,
    StoreDatabaseError,
    StoreError,
    StoreOperation,
    WrapInProgressError,
)
from .types import (
    AffectiveState,
    AssociationPair,
    AssociationStats,
    Episode,
    EpisodeType,
    PrepareWrapResult,
    RecallResult,
    SaveContinuityResult,
    StalePatternDict,
    StoreStatus,
    Tombstone,
    WrapPackageDict,
    WrapRecord,
    WrapResult,
)
from .audit import AuditTrail, AuditVerifyResult
from .schema import (
    DEFAULT_GRADUATING,
    DEFAULT_SCHEMA,
    FLOW_SCHEMA,
    SCHEMA_NAMES,
    SectionRole,
    SectionSpec,
    graduating_headings,
    heading_marker,
    name_for_schema,
    required_headings,
    schema_by_name,
    sections_by_role,
    validate_schema,
)
from .continuity import (
    format_wrap_package_text,
    prepare_wrap,
    validate_structure,
    validated_save_continuity,
)
from .graduation import (
    CrossSessionCollision,
    OmittedPattern,
    ProvenWithoutDeclaration,
    check_explanation_overlap,
    detect_pattern_omissions,
    detect_proven_without_declaration,
    detect_stale_patterns,
    extract_contradiction_declarations,
    extract_pattern_names,
    extract_proven_patterns,
    extract_session_co_citations,
    validate_graduations,
)
from .integrity import TOOLS, RESOURCES, verify_integrity, generate_integrity_file
from .spores import (
    ASCEND_BY_TYPE,
    DESCEND_BY_TYPE,
    VALID_TIERS,
    VALID_TYPES,
    Germination,
    ResolutionDict,
    SporeDict,
    SporeError,
    SporeStore,
    SporeType,
    Tier,
    germination_tier,
)
from .server import Server

__all__ = [
    "AnnealMemoryError",
    "Store",
    "StoreDatabaseError",
    "StoreError",
    "StoreOperation",
    "WrapInProgressError",
    "Server",
    "AuditTrail",
    "AuditVerifyResult",
    "AffectiveState",
    "AssociationPair",
    "AssociationStats",
    "Episode",
    "EpisodeType",
    "PrepareWrapResult",
    "RecallResult",
    "SaveContinuityResult",
    "StalePatternDict",
    "StoreStatus",
    "Tombstone",
    "WrapPackageDict",
    "WrapRecord",
    "WrapResult",
    "TOOLS",
    "RESOURCES",
    "SectionSpec",
    "SectionRole",
    "DEFAULT_SCHEMA",
    "FLOW_SCHEMA",
    "SCHEMA_NAMES",
    "schema_by_name",
    "name_for_schema",
    "DEFAULT_GRADUATING",
    "validate_schema",
    "graduating_headings",
    "required_headings",
    "sections_by_role",
    "heading_marker",
    "validate_structure",
    "prepare_wrap",
    "format_wrap_package_text",
    "validated_save_continuity",
    "validate_graduations",
    "check_explanation_overlap",
    "detect_stale_patterns",
    "extract_session_co_citations",
    "extract_pattern_names",
    "detect_pattern_omissions",
    "OmittedPattern",
    "CrossSessionCollision",
    "extract_proven_patterns",
    "extract_contradiction_declarations",
    "detect_proven_without_declaration",
    "ProvenWithoutDeclaration",
    "verify_integrity",
    "generate_integrity_file",
    "SporeStore",
    "SporeError",
    "SporeDict",
    "ResolutionDict",
    "SporeType",
    "Tier",
    "Germination",
    "germination_tier",
    "VALID_TYPES",
    "VALID_TIERS",
    "DESCEND_BY_TYPE",
    "ASCEND_BY_TYPE",
]
